### ISSUE TITLE
virtlet-image-translations does not work

### ISSUE THREAD

**Issue by nkwangjun** [futurewei-cloud/arktos#309]
**What happened**:
I want to deployment vm, first I create the configmap virtlet-image-translations :
```
images.yaml：

translations:
  - name: cirros
    url: https://github.com/mirantis/virtlet/releases/download/v0.9.3/cirros.img
  - name: fedora
    url: https://dl.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2
  - name: test
    url: http://localhost/cirros-0.3.5-x86_64-disk.img
```

then I want to use the image name virtlet.cloud/test to use the local image,like this

```
cirros.yaml:

apiVersion: v1
kind: Pod
metadata:
  name: cirros
spec:
  virtualMachine:
    name: cirros
    image: "virtlet.cloud/test"
    imagePullPolicy: IfNotPresent
    publicKey: nokey
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "1"
        memory: "1Gi"

```

The pod always be pending status, and there is errors in logs, sames the translation does not work.

```
E0523 06:51:55.374611    5608 remote_image.go:113] PullImage "virtlet.cloud/test:latest" from image service failed: rpc error: code = Unknown desc = error downloading "virtlet.cloud/test": Get https://virtlet.cloud/test: x509: certificate signed by unknown authority
E0523 06:51:55.374635    5608 kuberuntime_image.go:75] Pull image "virtlet.cloud/test:latest" failed: rpc error: code = Unknown desc = error downloading "virtlet.cloud/test": Get https://virtlet.cloud/test: x509: certificate signed by unknown authority
```

**Environment**:
- Arktos version (use `kubectl version`):
The latest version, master branch(2020-05-23)
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
root@arktos:~/work/src/github.com/arktos# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
- Kernel (e.g. `uname -a`):
```
root@arktos:~/work/src/github.com/arktos# uname -a
Linux arktos 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
