### ISSUE TITLE
The deletion process of the pod and VM is too slow

### ISSUE THREAD

**Issue by ZongbaoLiu** [futurewei-cloud/arktos#345]
**What happened**:
When I delete a container or VM, it takes at least half a minute.

**What you expected to happen**:
It should be completed within 10 seconds.

**How to reproduce it (as minimally and precisely as possible)**:
I create a pod with a yaml file
```
root@arktos:/home/arktos/arktos_file# cat nginx-1.yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: nginx-pod-1
  labels:
    name: nginx-container-1
spec:
  containers:
  - name: nginx-container-1
    image: nginx:1.7.9
root@arktos:/home/arktos/arktos_file# kubectl create -f nginx-1.yaml
pod/nginx-pod-1 created
```
When I delete this pod, it takes  about a minute.
```
root@arktos:/home/arktos/arktos_file# kubectl delete -f nginx-1.yaml
pod "nginx-pod-1" deleted
root@arktos:/home/arktos/arktos_file# kubectl get pods
NAME          HASHKEY              READY   STATUS        RESTARTS   AGE
nginx-pod-1   334082279037826436   0/1     Terminating   0          3m39s
root@arktos:/home/arktos/arktos_file# kubectl get pods
NAME          HASHKEY              READY   STATUS        RESTARTS   AGE
nginx-pod-1   334082279037826436   0/1     Terminating   0          4m35s
```
Similarly, when I delete a virtual machine, it takes about the same time.
Whether it is to delete a virtual machine or a pod, it should be completed in a very short time(maybe 10 second).

**Environment**:
- Arktos version (use `kubectl version`):
```
root@arktos:/home/arktos/arktos_file# kubectl version
Client Version: version.Info{Major:"0", Minor:"2+", GitVersion:"v0.2-72+0ee4f8288a73f4-dirty", GitCommit:"0ee4f8288a73f46341c156c4ea761f4883fbf36a", GitTreeState:"dirty", BuildDate:"2020-06-03T06:26:13Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"0", Minor:"2+", GitVersion:"v0.2-72+0ee4f8288a73f4-dirty", GitCommit:"0ee4f8288a73f46341c156c4ea761f4883fbf36a", GitTreeState:"dirty", BuildDate:"2020-06-03T06:26:13Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
root@arktos:/home/arktos/arktos_file# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
root@arktos:/home/arktos/arktos_file# uname -a
Linux arktos 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
