### ISSUE TITLE
scheduler unable to schedule Flannel pod in cluster bootstrapping process

### ISSUE THREAD

**Issue by h-w-chen** [futurewei-cloud/arktos#588]
**What happened**:
flannel cni pod is not scheduled

**What you expected to happen**:
flannel cni pods are scheduled and in running state to finish cni plugins installation, which is part of bootstrapping process.

**How to reproduce it (as minimally and precisely as possible)**:
1. comment out following line in hack/arktos-up.sh
```source ${KUBE_ROOT}/hack/arktos-cni.rc```
2. ensure there is no file under /etc/cni/net.d
3. bootstrap the cluster by ```./hack/arktos-up.sh```
4. wait till it is displaying ```Waiting for node ready at api server```
5. on another console, run
```
./cluster/kubectl.sh apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
```
6. look at the pod status by ```./cluster/kubectl.sh get pod -n kube-system kube-flannel-ds-xxxx -o yaml```, it returns
```yaml
...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-13T21:47:28Z"
    message: '0/1 nodes are available: 1 node runtime is not ready.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Guaranteed
```

**Anything else we need to know?**:
if arktos-up.sh was run without any change (so the bridge cni was installed and node was ready soon after), flannel deployment was able to deployed, and flannel cni pod was able to run (may eventually into crashloopbackoff state, but it is another question).

**Environment**:
- Arktos version (use `kubectl version`): GitCommit:"5069e78665708f7949af52a77aa8581998d573b0"
- Cloud provider or hardware configuration: GCP VM, ni-standard
- OS (e.g: `cat /etc/os-release`):Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.3.0-1032-gcp #34~18.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- Install tools: (slightly modified) arktos-up.sh
- Network plugin and version (if this is a network-related bug): flannel
- Others:
