### ISSUE TITLE
services of the default network get IP address assigned for external IPAM type

### ISSUE THREAD

**Issue by h-w-chen** [futurewei-cloud/arktos#763]
**What happened**:
The default network template specifies the service.ipam is External; DNS servcei of this network network still got ip address assigned by kuba-apiserver

**What you expected to happen**:
DNS serfice should have no clusterIP

**How to reproduce it (as minimally and precisely as possible)**:
1. prepare a default-network template, having content of
```json
{
    "metadata": {
        "name": "default",
        "finalizers": ["arktos.futurewei.com/network"]
    },
    "spec": {
        "type": "vpc",
        "service": {
             "ipam": "External"
        } 
    }
}
```
2. start single node arktos lab by 
```bash
export ARKTOS_NETWORK_TEMPLATE=<path-to-teh-default-network-template-file>
./hack/arktos-up.sh
```
3. prepare the local config file used by arktos-network-controller, with follwoing content
```yaml
apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:8080
  name: local
contexts:
- context:
    cluster: local
    user: ""
  name: local-ctx
current-context: local-ctx
kind: Config
preferences: {}
users: []
```
4. build arktos-network-controller and start it by following command
```bash
./_output/local/bin/linux/amd64/arktos-network-controller --kubeconfig=<path-to-the-above-config-file> --kube-apiserver-ip=<ip-addr-of-this-host>
```
5. then, looking at the DNS service of the default network
```bash
$ ./cluster/kubectl.sh get svc kubernetes-default
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)  
kubernetes-default   ClusterIP   10.0.0.166   <none>        443/TCP 
``` 

**Anything else we need to know?**:
For custom networks, instead of the default one, their DNS services won't have ip address assigned, just as expected.

**Environment**:
- Arktos version (use `kubectl version`): GitCommit:"94992457ec5098ae5af5b63da2eb20dae3c44803"
- Cloud provider or hardware configuration: local dev machine
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): 4.15.0-112-generic
- Install tools: arktos-up.sh
- Network plugin and version (if this is a network-related bug): flannel
- Others:
